// Theme initialization script to prevent FOUC (Flash of Unstyled Content)
(function() {
  'use strict';
  
  const THEME_STORAGE_KEY = 'pageblocks-theme';
  
  // Get stored theme or default to light
  function getStoredTheme() {
    try {
      const stored = localStorage.getItem(THEME_STORAGE_KEY);
      return stored && ['light', 'dark'].includes(stored) ? stored : 'light';
    } catch {
      return 'light';
    }
  }
  
  // Apply theme class to document element
  function applyTheme() {
    const theme = getStoredTheme();
    
    // Remove existing theme classes (using pattern matching for generated class names)
    const existingClasses = Array.from(document.documentElement.classList);
    existingClasses.forEach(className => {
      if (className.startsWith('theme_')) {
        document.documentElement.classList.remove(className);
      }
    });
    
    // Add the appropriate theme class
    // Note: The actual class names will be generated by createTheme, 
    // but we'll apply a temporary class that will be replaced by React
    if (theme === 'dark') {
      document.documentElement.classList.add('theme-dark-temp');
    } else {
      document.documentElement.classList.add('theme-light-temp');
    }
  }
  
  // Apply theme immediately
  applyTheme();
})(); 